version: "2"
services:
  todo:
    image: simple-todo-app
    container_name: todoApp
    ports:
    - 4000:4000/tcp
    depends_on:
    - dbTest

  dbTest:
    container_name: postgres-todo
    image: postgres:9.6
    hostname: postgres
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_DB=simple_todo_app_dev
